apiVersion: v2
name: recipe-extractor
type: application
description: A Helm chart for deploying the Recipe Parser application (Extraction Service + Recipe Service)
appVersion: "2.0.0"
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.0
home: https://github.com/juuwel/recipe-extractor
maintainers:
  - name: juuwel
